//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloPrincipal.InfraCcg2009.LinqCcg2009
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acusado
    {
        public int id_acusado { get; set; }
        public string nome { get; set; }
        public string cpfcnpj { get; set; }
        public string rg { get; set; }
        public string cnh { get; set; }
        public string renach { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string municipio { get; set; }
        public string uf { get; set; }
        public string cep { get; set; }
        public string fone { get; set; }
        public string email { get; set; }
        public string matricula { get; set; }
        public string pessoa_tipo { get; set; }
        public Nullable<int> IdAcusado { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string PessoaTipo { get; set; }
    }
}
