//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloPrincipal.InfraCcg2009.LinqCcg2009
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ccg2009Conexao : DbContext
    {
        public Ccg2009Conexao()
            : base("name=Ccg2009Conexao")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acusado> Acusado { get; set; }
        public virtual DbSet<Andamento> Andamento { get; set; }
        public virtual DbSet<Comissao> Comissao { get; set; }
        public virtual DbSet<Denuncia> Denuncia { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<NadaConsta> NadaConsta { get; set; }
        public virtual DbSet<Processo> Processo { get; set; }
        public virtual DbSet<ProcessoAcusado> ProcessoAcusado { get; set; }
        public virtual DbSet<ProcessoTestemunha> ProcessoTestemunha { get; set; }
        public virtual DbSet<Testemunha> Testemunha { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoNadaConsta> TipoNadaConsta { get; set; }
        public virtual DbSet<TipoProcesso> TipoProcesso { get; set; }
        public virtual DbSet<Tramitar> Tramitar { get; set; }
    }
}
