//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloPrincipal.InfraCcg2009.LinqCcg2009
{
    using System;
    using System.Collections.Generic;
    
    public partial class NadaConsta
    {
        public int id_nada_consta { get; set; }
        public string nome { get; set; }
        public string numero_documento { get; set; }
        public Nullable<System.DateTime> data_consulta { get; set; }
        public Nullable<int> numero_ocorrencias { get; set; }
        public string servidor { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> numero { get; set; }
        public string motivo { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string documento_solicitacao { get; set; }
    }
}
