//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloPrincipal.InfraCcg2009.LinqCcg2009
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processo
    {
        public int id_processo { get; set; }
        public int Numero { get; set; }
        public int Ano { get; set; }
        public int id_tipo_processo { get; set; }
        public int id_tipo_documento { get; set; }
        public string id_municipio { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> data_instauracao { get; set; }
        public Nullable<System.DateTime> data_encerramento { get; set; }
        public string placa { get; set; }
        public string renavam { get; set; }
        public string presidente_comissao { get; set; }
        public string secretario_comissao { get; set; }
        public string membro_comissao { get; set; }
        public string local_fato { get; set; }
        public Nullable<System.DateTime> data_fato { get; set; }
        public string portaria_instautaracao { get; set; }
        public string historico { get; set; }
        public string portaria_encerramento { get; set; }
        public string punicao { get; set; }
        public string andamento { get; set; }
        public Nullable<int> id_comissao { get; set; }
        public string resumo_punicao { get; set; }
        public string Status { get; set; }
    }
}
