//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloPrincipal.InfraCcg2009.LinqCcg2009
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessoTestemunha
    {
        public int id_processo { get; set; }
        public int id_testemunha { get; set; }
    }
}
