//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloPrincipal.InfraCorregedoria2018.LinqCorregedoria2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certidao
    {
        public int idCertidao { get; set; }
        public string nome { get; set; }
        public string cpfcnpj { get; set; }
        public string validador { get; set; }
        public Nullable<System.DateTime> dataEmissao { get; set; }
        public Nullable<System.DateTime> dataValidade { get; set; }
        public Nullable<int> idcorregedor { get; set; }
    
        public virtual Corregedor Corregedor { get; set; }
    }
}
