//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloPrincipal.InfraCorregedoria2018.LinqCorregedoria2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corregedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Corregedor()
        {
            this.Certidao = new HashSet<Certidao>();
        }
    
        public int idcorregedor { get; set; }
        public string nome { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> datainicio { get; set; }
        public Nullable<System.DateTime> datafinal { get; set; }
        public string status { get; set; }
        public byte[] Imagem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certidao> Certidao { get; set; }
    }
}
