//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloPrincipal.InfraCorregedoria2018.LinqCorregedoria2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pena
    {
        public int idPena { get; set; }
        public Nullable<int> idProcessoAcusado { get; set; }
        public string punicao { get; set; }
        public Nullable<System.DateTime> dataPublicacao { get; set; }
        public string portaria { get; set; }
        public string ativo { get; set; }
    
        public virtual ProcessoSindicado ProcessoSindicado { get; set; }
    }
}
