//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloPrincipal.InfraCorregedoria2018.LinqCorregedoria2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessoTestemunha
    {
        public int idProcessoTestemunha { get; set; }
        public Nullable<int> idProcesso { get; set; }
        public Nullable<int> idPessoa { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Processo Processo { get; set; }
    }
}
